### ISSUE TITLE
Reported errors with subset of DICOM Physio files

### ISSUE THREAD

**Issue by jmtyszka** [adolphslab/mriphysio#2]
Hi Mike,

So I am trying to run your script that takes the dcm files and converts them into tsv, but it's only working on about half of our physio dcm files. I have attached two files:

IM-0001-0001 - this one does not work. Error message:

Traceback (most recent call last):
  File "/dcm2physio.py", line 142, in <module>
    main()
  File "/dcm2physio.py", line 105, in main
    t_puls.append(float(parts[0]))
ValueError: could not convert string to float: '>'

IM-0003-0001 - this one works fine, and it's from the same subject but a different task.

I have tried two other files, and one of them gives the same error, but it tries to convert a question mark '?' to float. I looked at the headers for all these files, and nothing seemed to be related with the error. dicomread() on matlab only returns empty doubles for these files, so I am not sure what the script is trying to parse through.

Let me know if you have any thoughts, or questions, etc.

Thanks!
Marcos

**Comment by jmtyszka** [comment]
Fixed in v1.2 by adapting CMRR official parsing logic for python3
